// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lahyziwwoiclkmqjtfha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxhaHl6aXd3b2ljbGttcWp0ZmhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3ODk5ODMsImV4cCI6MjA4NTM2NTk4M30.uFrMaVqM2SdPOujC8D1Jm32_hMgnIs2VK12zCFiQB-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});